server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie  #用于指定注册到Eureka Server上的应用名称

eureka:
  client:
    serviceUrl:
      defaultZooe: http://localhost:8761/eureka/
  instance:
    perfer-ip-address: true #将自己IP注册到Eureka Server

feign:
  hystrix:
    enabled: true #Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开。需要在配置文件中配置打开它


